{% set name = "tables-io" %}
{% set version = "0.7.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace("-", "_") }}-{{ version }}.tar.gz
  sha256: 3a97485f31764a1363766f77e2b6ea1d765505eb7d75a3feadf96333fe422635

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv
  noarch: python

requirements:
  host:
    - python >=3.6
    - pip
    - setuptools_scm

  run:
    - python >=3.6
    - numpy
    - astropy
    - h5py
    - pandas
    - pyarrow
    - pytables

test:
  imports:
    - tables_io

about:
  home: http://github.com/LSSTDESC/tables_io
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Input/output and conversion interfaces for tabular data formats.
  description: |
    Input/output and conversion interfaces for tabular data formats.
  dev_url: https://github.com/LSSTDESC/tables_io

extra:
  recipe-maintainers:
    - eacharles
    - brianv0
