{% set name = "tables-io" %}
{% set version = "0.9.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 7ce4c844a4aac837259d62520b6e7cc44b6a5d520cb546009bbfb978dc27a899

build:
  number: 0

outputs:
  - name: {{ name }}
    script: build_base.sh
    build:
      noarch: python
    requirements:
      host:
        - python >=3.6
        - pip
        - setuptools_scm

      run:
        - python >=3.6
        - numpy
    test:
      imports:
        - tables_io

  - name: {{ name }}-full
    build:
      noarch: python
    requirements:
      run:
        - {{ pin_subpackage('tables-io', max_pin='x.x.x') }}
        - astropy
        - h5py
        - pandas
        - pyarrow
        - pytables
    test:
      imports:
        - tables_io
        - astropy
        - h5py
        - pandas
        - pyarrow

about:
  home: http://github.com/LSSTDESC/tables_io
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Input/output and conversion interfaces for tabular data formats.
  description: |
    Input/output and conversion interfaces for tabular data formats.
  dev_url: https://github.com/LSSTDESC/tables_io

extra:
  recipe-maintainers:
    - eacharles
    - brianv0
